version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Europe/Sofia"
    labels:
      - "dependencies"
    assignees:
      - Sagar-Kap
    commit-message:
      prefix: "chore(deps): "

  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Europe/Sofia"
    labels:
      - "dependencies"
    assignees:
      - Sagar-Kap
    commit-message:
      prefix: "chore(deps): "
