version: "3"

silent: true

tasks:
  default:
    desc: List all the available commands
    summary: |
      List all the available commands.

      This command will print a nice and helpful list of all available commands
      and their purposes to STDOUT.
    cmd: task --list

  setup:
    desc: Setup the local development environment
    summary: |
      Setup the dev environment.

      This command will automatically setup the development environment for you.
      It will setup the pre-commit hooks, build the appropriate Docker commands
      and more such commands will be automated using this command.
    cmds:
      - pre-commit install --install-hooks
      - pre-commit install --hook-type commit-msg
      - task: setup:website

  qa-checks:
    desc: Run all sorts of QA checks on the source code.
    summary: |
      Run all sorts of QA checks on the source code.

      This task will intelligently run all sorts of QA checks on the source
      code. The tools used to perform the task are ESLint, Prettier and more.
    cmds:
      - task: qa-checks:website
      - pre-commit run --all-files

  dev:
    desc: Run development version of the project.
    summary: |
      This task will run the local development version of the website.
    dir: ./website
    cmd: pnpm run dev

  ##########################################################################
  # Internal dependencies for setting up the dev environment
  ##########################################################################

  setup:website:
    internal: true
    desc: Setup the dev environment for the Front End
    dir: ./website
    cmd: pnpm install
    sources:
      - package.json
    generates:
      - pnpm-lock.yaml

  ##########################################################################
  # Tasks to format the code for different services
  ##########################################################################

  qa-checks:website:
    internal: true
    dir: ./website
    cmds:
      - pnpm run lint
      - pnpm run format
