import type { Metadata } from "next";
import { ibm_plex_mono } from "@styles/fonts";
import "@styles/globals.css";
import Navbar from "@components/layout/navbar";
import Footer from "@components/layout/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={ibm_plex_mono.className}>
      <body
        className="bg-bg-1 text-white flex 
        flex-col"
      >
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
